### ISSUE TITLE
Siging-job request using an ECC certificate

### ISSUE THREAD

**Issue by oysteinthoensisjord** [digipost/signature-api-client-dotnet#446] opened 2024-09-05 06:53 UTC
We're trying to make a signing job using an ECC certificate. This fails with the exception message
`Specified certificate with fingerprint "removed thumbprint" is not a valid RSA asymetric key.`

So I guess the library is limited to RSA certificates. When will you start supporting ECC certificates? As far as I know it is considered more secure than RSA.

**Comment by EirikWulff** [comment] 2024-09-05 10:19
BuyPass has the option to use ECC/NIST P-256 key for "Standard certificate - customer generate key" and when ordering a test certificate (with your own CSR). Neither of those options has any kind of warning that it limits the usability of the certificate.

I think this has the potential to be a real problem, especially since all documentation just assumes RSA without mentioning it.

**Comment by runeflobakk** [comment] 2024-09-05 13:32
Are you familiar with using `curl` and perhaps `openssl`? We don't have an ECC-enterprise certificate at hand here, but we would like to verify that ECC certificates are handled as-is in our API.

Would you be willing to do a request to
```
GET https://api.signering.posten.no/api/{your-organization-number}
```
using curl in order to check if your ECC certificate is allowed by our API? You would need to provide your cert private and public key as `--key` `--cert` respectively, and instruct curl to not do standard TLS validation of Posten signering API certificate (it also exposes a enterprise certificate, not a standard TLS cert, and which curl does not recognize) using the somewhat spooky looking `--insecure` flag.

If your request is authenticated in the API, you will get a plain text response just echoing your organization number.

**Comment by hernil** [comment] 2024-09-05 13:41
Hello! 

I'm attaching a modified version of some internal developer docs (not translated - apologies) that should hopefully help you do the GET-request @runeflobakk mentioned and verify that our server side is capable of handling ECC certificates. It assumes a keystore in the pkcs12 format but should work with raw pem files if you just skip a few steps. 

# Verifisere API-tilkobling med curl

Fra tid til annen kan det være kjekt å gjøre enkelte kall mot API-et med curl. Under følger en liten forklaring. 

## Litt om nøkler og sertifikater

Vi starter med en `client-keystore.p12` som er i pkcs12-format[^1]. 

Keystoren inneholder en privat nøkkel samt et client-sertifikat og medfølgende sertifikatkjede. Herfra har vi et par alternativer. I alle tilfeller vil du mest sannsynlig promptes for passord på storen så ha det klart. Vi kan eksportere hele greia til pem-format og bruke det direkte.
```
openssl pkcs12 --noenc --in client-keystore.p12 --out keystore.pem
```
`keystore.pem` inneholder da både privat nøkkel og klientsertifikatkjede.  

Eller vi kan splitte disse komponentene hver for seg om det er hensiktsmessig. 

Privat nøkkel
```
openssl pkcs12 --noenc --in client-keystore.p12 --out privateKey.pem --nocerts
``` 

Klientsertifikatkjede uten privat nøkkel
```
openssl pkcs12 --noenc --in client-keystore.p12 --out clientCertificate.pem --nokeys 
```

`--noenc` sier at vi ikke skal kryptere outputen. 

## Selve curl-kallet

Dette eksempelet bruker prod-miljøet som endepunkt. Dette kan selvfølgelig endres til passende miljø. 

```
curl https://api.signering.posten.no/api/984661185 --key privateKey.pem --cert clientCertificate.pem --insecure
```

`984661185` i endepunktet her refererer til organisasjonsnummeret som virksomhetssertifikatet er utstedt til. 

Om man har valgt å ikke splitte sertifikat og den private nøkkelen så brukes `-E keystore.pem` som parameter. Altså blir kallet:
```
curl https://api.signering.posten.no/api/984661185 -E keystore.pem --insecure
```

Forventet output i vårt helt konkrete tilfelle er
```
You are 988015814, operating on behalf of 984661185%
```

`--insecure` er påkrevd da sertifikatet vårt på serversiden ikke er utstedt til hostens adresse, men til virksomheten. Noe som er en litt uvanlig måte å gjøre ting på når man snakker over internett på den måten. 

`--verbose` kan være kjekt for å få ut ekstra informasjon om kallet og handshake som foregår i forkant.  

[^1]: Dersom man har en keystore i det gode gamle jce-formatet så kan følgende kommando konvertere: `keytool -importkeystore -srckeystore client-keystore.jce -destkeystore client-keystore.p12 -deststoretype pkcs12`

**Comment by EirikWulff** [comment] 2024-09-05 13:49
That is interesting. I'll try to check our ECC certificate tomorrow

**Comment by EirikWulff** [comment] 2024-09-06 07:27
I can confirm that using curl and the ECC certificate works perfectly:
```
curl https://api.signering.posten.no/api/974760223 --key privateKey.pem --cert clientCertificate.pem --insecure --verbose
* Host api.signering.posten.no:443 was resolved.
* IPv6: (none)
* IPv4: 51.124.140.180
*   Trying 51.124.140.180:443...
* Connected to api.signering.posten.no (51.124.140.180) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=NO; O=POSTEN NORGE AS; OU=Digipost; CN=POSTEN NORGE AS; serialNumber=984661185
*  start date: Nov 10 15:11:37 2021 GMT
*  expire date: Nov 10 22:59:00 2024 GMT
*  issuer: C=NO; O=Buypass AS-983163327; CN=Buypass Class 3 CA 3
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* using HTTP/1.x
> GET /api/974760223 HTTP/1.1
> Host: api.signering.posten.no
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Date: Fri, 06 Sep 2024 07:25:42 GMT
< Content-Type: text/plain
< Cache-Control: no-cache, no-store, no-transform
< Vary: Accept-Encoding
< Content-Length: 17
< 
* Connection #0 to host api.signering.posten.no left intact
You are 974760223%   
```

**Comment by EirikWulff** [comment] 2024-09-06 07:30
Sadly, the same cannot be said for Samarbeidsportalen. Perhaps the backend can handle ECC, but the frontend does not.

**Comment by runeflobakk** [comment] 2024-09-06 08:01
@EirikWulff Thank you for verifying! This confirms our suspicion that the problem is actually isolated to the library, and should not be that much work to fix after all. At least on our part, but I understand there are issues with these certificates in Samarbeidsportalen 😐

I am not that acquinted with Samarbeidsportalen. What are you trying to do there which denies your ECC certificate? I can make some enquiries about this.

**Comment by EirikWulff** [comment] 2024-09-06 10:20
@runeflobakk The Samarbeidsportalen Web UI will not let me upload the ECC certificate to an integration, probably due to some frontend code hardcoded for RSA. We get two different error messages, one when the integration is in edit mode, the other when it is just viewed. We can upload the certificate in both states. I have just tested this in the test environment, and get these error messages:

1. Edit mode: **Valideringsfeil [keys]. The minimum length is 2048**
2. View mode: **Valideringsfeil [keys]: The algorithm must be RS256 or RS512**

**Comment by EirikWulff** [comment] 2024-09-06 12:29
@runeflobakk I don't have skills with dotNet, so perhaps @oysteinthoensisjord could take a look at it? 
BTW: Did the intel say anything about ECC support for other backends, like Maskinporten? The JWT request will have to be run with other properties, which are not documented at this point.

**Comment by hernil** [comment] 2024-09-06 13:27
Hey, 
I tried to do a very quick fix to see if that is enough. It should be released as version 9.1.0-beta. Could you have a look and see if it solves the problem for you? 

If not we will have to schedule some time to have a deeper look at some point, or someone could take a crack at it. 

Sorry for not testing this properly beforehand I figured it was more useful to get this into your hands than to tackle generating our own ECC test certificate on a friday afternoon.

**Comment by runeflobakk** [comment] 2024-09-10 17:03
I have confirmed that Maskinporten does _not_ support ECC enterprise certificates at this point. Further enquiries regarding Maskinporten should be directed to [Digdir](https://samarbeid.digdir.no/digital-postkasse/kontakt-oss/83).

Integrating with the Posten signering API does not mandate the use of Maskinporten, and using 9.1.0-beta of this library should enable use of an ECC certificate. Though if other services you wish to use require use of Maskinporten, then it seems at this point you need to acquire an RSA enterprise certificate.

**Comment by oysteinthoensisjord** [comment] 2024-09-16 10:39
> Hey, I tried to do a very quick fix to see if that is enough. It should be released as version 9.1.0-beta. Could you have a look and see if it solves the problem for you?
> 
> If not we will have to schedule some time to have a deeper look at some point, or someone could take a crack at it.
> 
> Sorry for not testing this properly beforehand I figured it was more useful to get this into your hands than to tackle generating our own ECC test certificate on a friday afternoon.

I've tested it, but it seems like the package struggled to extract the private key or something. For now we'll be using RSA due to limitations in Maskinporten. So I haven't tested 9.1.0-beta any further.

**Comment by hernil** [comment] 2024-09-16 11:35
Would you mind attaching a stack trace for us before moving to RSA certificates? 😊

**Comment by oysteinthoensisjord** [comment] 2024-09-16 13:20
> Would you mind attaching a stack trace for us before moving to RSA certificates? 😊

Sure.. I loaded the ECC cert as an instance of X509Certificate2. When using this object and intitiating the method  "client.Create(job)" the result is this stack trace 

`Digipost.Signature.Api.Client.Core.Exceptions.XmlParseException: Kunne ikke bygge Xml for signatur.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Security.Cryptography.ECDsaCng' to type 'System.Security.Cryptography.RSA'.
   at System.Security.Cryptography.RSAPKCS1SignatureFormatter.SetKey(AsymmetricAlgorithm key)
   at System.Security.Cryptography.SignatureDescription.CreateFormatter(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.ComputeSignature()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.CreateXadesSignature()
   at Digipost.Signature.Api.Client.Core.Internal.Asice.AsiceSignature.SignatureGenerator.Xml()`

**Comment by hernil** [comment] 2024-09-18 12:54
Thanks! 

Looks like we need to do some more work to our client for this to work correctly. Considering that Maskinporten does not support these certificates anyway we will not prioritize this for now. I have updated [our documentation](https://signering-docs.readthedocs.io/en/latest/client-integration/buy-enterprise-certificates.html) to reflect the RSA requirement explicitly.

**Closed by hernil** 2024-09-18 12:54 UTC
